[webservers]
# Première machine
192.168.122.128 ansible_user=cheikh ansible_ssh_private_key_file=/home/cheikh/.ssh/id_ansible ansible_ssh_common_args='-o StrictHostKeyChecking=no'

# Deuxième machine
192.168.122.130 ansible_user=cheikh ansible_ssh_private_key_file=/home/cheikh/.ssh/id_ansible ansible_ssh_common_args='-o StrictHostKeyChecking=no'
