all:
  hosts:
    192.168.122.128:
      ansible_user: cheikh
      ansible_ssh_private_key_file: /var/lib/jenkins/.ssh/id_ansible
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    192.168.122.130:
      ansible_user: cheikh
      ansible_ssh_private_key_file: /var/lib/jenkins/.ssh/id_ansible
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
